-- Copyright (©) 2024 - Shivam Kumar Jha - All Rights Reserved, Proprietary and confidential
-- Unauthorised copying of this file, via any medium is strictly prohibited

CREATE TABLE class (
  id   SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name TEXT NOT NULL
);

CREATE TABLE section (
  id      SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name    TEXT NOT NULL,
  classid SMALLINT NOT NULL REFERENCES class (id)
);

CREATE TABLE session (
  id        SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name      TEXT NOT NULL,
  startdate INTEGER NOT NULL,
  enddate   INTEGER NOT NULL
);

CREATE TABLE users (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 3),
  email      TEXT UNIQUE,
  mobilenum  TEXT UNIQUE,
  firstname  TEXT CHECK (LENGTH(firstname) <= 100) NOT NULL,
  lastname   TEXT CHECK (LENGTH(lastname) <= 100),
  profilepic TEXT CHECK (LENGTH(profilepic) <= 250)
);

CREATE TABLE student (
  id        INTEGER PRIMARY KEY REFERENCES users (id),
  sectionid SMALLINT NOT NULL REFERENCES section (id)
);
