-- Copyright (©) 2024 - Shivam Kumar Jha - All Rights Reserved, Proprietary and confidential
-- Unauthorised copying of this file, via any medium is strictly prohibited
-- Auto generated, Don't edit by hand

-- ==> schema/1.master_data.m.sql <==

CREATE TABLE class (
  id   SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name TEXT NOT NULL
);

CREATE TABLE section (
  id      SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name    TEXT NOT NULL,
  classid SMALLINT NOT NULL REFERENCES class (id)
);

CREATE TABLE session (
  id        SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name      TEXT NOT NULL,
  startdate INTEGER NOT NULL,
  enddate   INTEGER NOT NULL
);

CREATE TABLE users (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 3),
  email      TEXT UNIQUE,
  mobilenum  TEXT UNIQUE,
  firstname  TEXT CHECK (LENGTH(firstname) <= 100) NOT NULL,
  lastname   TEXT CHECK (LENGTH(lastname) <= 100),
  profilepic TEXT CHECK (LENGTH(profilepic) <= 250)
);

CREATE TABLE student (
  id        INTEGER PRIMARY KEY REFERENCES users (id),
  sectionid SMALLINT NOT NULL REFERENCES section (id)
);

-- ==> schema/2.attendance.m.sql <==

CREATE TABLE attendance (
  studentid INTEGER REFERENCES student (id),
  date      INTEGER,
  sectionid SMALLINT NOT NULL REFERENCES section (id),
  isabsent  BOOLEAN,
  ishalfday BOOLEAN,
  islate    BOOLEAN,
  PRIMARY KEY (studentid, date)
);

CREATE TABLE offday (
  date        INTEGER,
  classid     SMALLINT REFERENCES class (id),
  sectionid   SMALLINT REFERENCES section (id),
  isholiday   BOOLEAN,
  isweekend   BOOLEAN,
  ishalfday   BOOLEAN,
  description TEXT CHECK (LENGTH(description) <= 100)
);

-- ==> schema/3.payment_collection.m.sql <==

CREATE TABLE payment (
  id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  studentid  INTEGER REFERENCES student (id),
  dueamount  SMALLINT NOT NULL,
  paidamount SMALLINT NOT NULL,
  concession SMALLINT,
  latefees   SMALLINT,
  status     SMALLINT NOT NULL CHECK (status > 0 AND status < 4),
  sectionid  SMALLINT NOT NULL REFERENCES section (id),
  paiddate   INTEGER
);

CREATE TABLE paymenthistory (
  paymentdate INTEGER NOT NULL,
  studentid   INTEGER NOT NULL,
  amount      SMALLINT NOT NULL,
  mode        SMALLINT NOT NULL CHECK (mode > 0 AND mode < 4),
  collectedby INTEGER,
  status      SMALLINT NOT NULL CHECK (status > 0 AND status < 4),
  paymentid   INTEGER NOT NULL REFERENCES payment (id)
);

CREATE TABLE receiptparticular (
  paymentid      INTEGER PRIMARY KEY REFERENCES payment (id),
  particularname TEXT NOT NULL,
  amount         SMALLINT NOT NULL
);

CREATE TABLE feedetail (
  id      SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name    TEXT,
  duedate INTEGER
);

CREATE TABLE classfee (
  feedetailid SMALLINT REFERENCES feedetail (id),
  sectionid   SMALLINT REFERENCES section (id),
  PRIMARY KEY (feedetailid, sectionid)
);

CREATE TABLE feesparticular (
  id          SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  name        TEXT NOT NULL,
  amount      SMALLINT NOT NULL,
  frequency   SMALLINT NOT NULL CHECK (frequency > 0 AND frequency < 4),
  optional    BOOLEAN,
  variable    BOOLEAN,
  feedetailid INTEGER NOT NULL REFERENCES feedetail (id)
);

CREATE TABLE feeconfig (
  feeparticularid SMALLINT REFERENCES feesparticular (id),
  studentid       INTEGER REFERENCES student (id),
  amount          SMALLINT,
  applicable      BOOLEAN,
  PRIMARY KEY (feeparticularid, studentid)
);
